# Generated by Django 3.2.12 on 2022-03-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0003_auto_20220328_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilgi',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='kisiresmi/', verbose_name='kisi resmi ekleyin'),
        ),
    ]
