# Generated by Django 3.2.12 on 2022-04-13 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0004_bilgi_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilgi',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anasayfa.ogr'),
        ),
    ]
